apiVersion: v1
kind: Service
metadata:
  name: realstate-web-service
  labels:
    app: realstate-web
spec:
  selector:
    app: realstate-web
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
