# Generated by Django 4.2.5 on 2023-11-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='agent')),
            ],
        ),
    ]
