# Generated by Django 4.2.5 on 2023-11-08 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('basecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='master.basecontent')),
                ('subname', models.CharField(max_length=225)),
                ('Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.category')),
            ],
            bases=('master.basecontent',),
        ),
    ]
