# Generated by Django 4.2.5 on 2023-11-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_teamprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamprofile',
            name='image',
            field=models.ImageField(upload_to='team'),
        ),
    ]
